export type Env = {
  readonly NODE_ENV: "development" | "test" | "production";
  readonly APP_NAME: string;
  readonly HOST: string;
  readonly PORT: number;
  readonly PUBLIC_URL: string;
  readonly TRUST_PROXY: boolean;
  readonly SUPPORT_EMAIL: string;
  readonly DATABASE_URL: string;
  readonly DATABASE_POOL_MIN: number;
  readonly DATABASE_POOL_MAX: number;
  readonly REDIS_URL: string | undefined;
  readonly LOG_LEVEL: "debug" | "info" | "warn" | "error";
  readonly LOG_FORMAT: "pretty" | "json";
  readonly OTEL_ENABLED: boolean;
  readonly SENTRY_DSN: string | undefined;
  readonly CORS_ORIGINS: readonly string[];
  readonly RATE_LIMIT_JSON: unknown;
  readonly FEATURE_FLAGS: readonly string[];
  readonly ALLOWED_TENANTS: readonly string[];
  readonly PAYMENTS_PROVIDER: "mock" | "stripe";
  readonly STRIPE_SECRET_KEY: string | undefined;
  readonly WEBHOOK_ENDPOINT: string | undefined;
  readonly WORKER_CONCURRENCY: number;
  readonly JOB_QUEUES: readonly string[];
  readonly ENABLE_SIGNUPS: boolean;
  readonly SESSION_SECRET: string;
};
export declare function loadEnv(env?: Record<string, string | undefined>): Env;
export default loadEnv;
